//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rensoft.ManxAds.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rensoft.ManxAds.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;body style=&quot;color: #333333&quot;&gt;
        ///&lt;table width=&quot;550&quot; border=&quot;0&quot; cellpadding=&quot;10&quot; cellspacing=&quot;0&quot; style=&quot;background-color: #F6F6FF; border: 1px #6D98CD solid&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;
        ///		&lt;a style=&quot;font-size: 16px; font-family: Arial, Helvetica, sans-serif&quot; href=&quot;http://www.manxads.com/&quot;&gt;&lt;img src=&quot;http://www.manxads.com/Email/Logo.gif&quot; alt=&quot;ManxAds.com&quot; width=&quot;360&quot; height=&quot;60&quot; border=&quot;0&quot; /&gt;&lt;/a&gt;
        ///		&lt;div style=&quot;font-size: 16px; font-family: Arial, Helvetica, sans-serif; margin-top: 10px; margin-bottom: 10px&quot;&gt;&lt;a  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListingAbuseForReporter {
            get {
                return ResourceManager.GetString("ListingAbuseForReporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;body style=&quot;color: #333333&quot;&gt;
        ///&lt;table width=&quot;550&quot; border=&quot;0&quot; cellpadding=&quot;10&quot; cellspacing=&quot;0&quot; style=&quot;background-color: #F6F6FF; border: 1px #6D98CD solid&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;
        ///		&lt;a style=&quot;font-size: 16px; font-family: Arial, Helvetica, sans-serif&quot; href=&quot;http://www.manxads.com/&quot;&gt;&lt;img src=&quot;http://www.manxads.com/Email/Logo.gif&quot; alt=&quot;ManxAds.com&quot; width=&quot;360&quot; height=&quot;60&quot; border=&quot;0&quot; /&gt;&lt;/a&gt;
        ///		&lt;div style=&quot;font-size: 16px; font-family: Arial, Helvetica, sans-serif; margin-top: 10px; margin-bottom: 10px&quot;&gt;&lt;a  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListingAbuseForSeller {
            get {
                return ResourceManager.GetString("ListingAbuseForSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The following listings have been reported as violating the listing policy.&lt;/p&gt;
        ///&lt;table cellpadding=&quot;3&quot; cellspacing=&quot;0&quot; border=&quot;1&quot;&gt;
        ///    &lt;tr bgcolor=&apos;#f3f4ff&apos;&gt;
        ///        &lt;th align=&quot;left&quot;&gt;Listing&lt;/th&gt;
        ///        &lt;th align=&quot;left&quot;&gt;Votes&lt;/th&gt;
        ///        &lt;th align=&quot;left&quot;&gt;Actions&lt;/th&gt;
        ///    &lt;/tr&gt;
        ///    {0}
        ///&lt;/table&gt;.
        /// </summary>
        internal static string ListingAbuseReportEmail {
            get {
                return ResourceManager.GetString("ListingAbuseReportEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;body style=&quot;color: #333333&quot;&gt;
        ///&lt;table width=&quot;550&quot; border=&quot;0&quot; cellpadding=&quot;10&quot; cellspacing=&quot;0&quot; style=&quot;background-color: #F6F6FF; border: 1px #6D98CD solid&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;
        ///		&lt;a style=&quot;font-size: 16px; font-family: Arial, Helvetica, sans-serif&quot; href=&quot;http://www.manxads.com/&quot;&gt;&lt;img src=&quot;http://www.manxads.com/Email/Logo.gif&quot; alt=&quot;ManxAds.com&quot; width=&quot;360&quot; height=&quot;60&quot; border=&quot;0&quot; /&gt;&lt;/a&gt;
        ///		&lt;div style=&quot;font-size: 16px; font-family: Arial, Helvetica, sans-serif; margin-top: 10px; margin-bottom: 10px&quot;&gt;&lt;a  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListingDeleteTemplate {
            get {
                return ResourceManager.GetString("ListingDeleteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;body style=&quot;color: #333333&quot;&gt;
        ///&lt;table width=&quot;550&quot; border=&quot;0&quot; cellpadding=&quot;10&quot; cellspacing=&quot;0&quot; style=&quot;background-color: #F6F6FF; border: 1px #6D98CD solid&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;
        ///		&lt;a style=&quot;font-size: 16px; font-family: Arial, Helvetica, sans-serif&quot; href=&quot;http://www.manxads.com/&quot;&gt;&lt;img src=&quot;http://www.manxads.com/Email/Logo.gif&quot; alt=&quot;ManxAds.com&quot; width=&quot;360&quot; height=&quot;60&quot; border=&quot;0&quot; /&gt;&lt;/a&gt;
        ///		&lt;div style=&quot;font-size: 16px; font-family: Arial, Helvetica, sans-serif; margin-top: 10px; margin-bottom: 10px&quot;&gt;&lt;a  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListingExpiryTemplate {
            get {
                return ResourceManager.GetString("ListingExpiryTemplate", resourceCulture);
            }
        }
    }
}
